# -*- coding: utf-8 -*-
"""tugas1_ddp_rabu_011012210_SI06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/starlight22106/PEMWEB/blob/main/tugas1_ddp_rabu_011012210_SI06.ipynb
"""

p1 = {'nama':'Budi','produk': 'TV', 'jumlah': 3}
p2 = {'nama':'Ani','produk': 'AC','jumlah': 4}
p3 = {'nama':'Siti','produk': 'Kulkas','jumlah': 2}
p4 = {'nama':'Dewi','produk': 'AC','jumlah': 5}
p5 = {'nama':'Andi','produk': 'Kulkas','jumlah': 7}
p6 = {'nama':'Dedi','produk': 'AC','jumlah': 1}
p7 = {'nama':'Sri','produk': 'TV','jumlah': 4}

ar_pelanggan =[p1,p2,p3,p4,p5,p6,p7]

for pelanggan in ar_pelanggan:
  for p in pelanggan:
    #harga satuan
    if pelanggan ['produk'] == 'TV':
      harga_satuan =5000000
    elif pelanggan ['produk'] == 'AC':
      harga_satuan =6000000
    else:
      harga_satuan =700000

    #harga kotor 
    harga_kotor = pelanggan['jumlah'] * harga_satuan

    #diskon
    if pelanggan['jumlah'] >=3 and pelanggan ['produk'] == 'kulkas':
      diskon =0.2 * harga_kotor
    else:
      diskon =0.05 * harga_kotor
      
    #PPN
    ppn = 0.11 * (harga_kotor - diskon)
    
    #harga bayar
    harga_bayar = (harga_kotor + ppn) - diskon
    print(p,':',pelanggan[p])
    
  print('harga satuan\t:',harga_satuan,
      '\nharga kotor\t:',harga_kotor,
      '\ndiskon\t\t:',diskon,
      '\nPPN\t\t\t:',ppn,
      '\nharga bayar\t:',harga_bayar,
      '\n-------------------------------')